/*
 * File: app/view/LogwinViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('login.view.LogwinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.logwin',

    onSignIn: function(button, e, eOpts) {
        //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Geting data on the from <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

        var username = Ext.getCmp('i_userid').value;
        var password = Ext.getCmp('i_pass').value;
        var getdataserver = '';

        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Server Connection <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

        var httpc = new XMLHttpRequest();
        //var url='https://ptsv2.com/t/26sh3-1578967376/post';
        var url ='php/api.php';
        httpc.open("POST", url, true);

        httpc.onreadystatechange = (e) => {  // check the connection
            if(httpc.readyState == 4 && httpc.status == 200)
            {
                console.log(httpc.responseText);
                getdataserver = httpc.responseText;
                if(getdataserver == "rid777")
                {
                    // >>>>>>>>>>>>>>>>> If Not Found or any error <<<<<<<<<<<<<<<<<
                    var vv = Ext.getCmp('l_status').setText('Status: Wrong user name and password');
                    alert('Wrong user name and password');
                }else
                {
                    // >>>>>>>>>>>>>>>>> If No error and connection is successful <<<<<<<<<<<<<<<<<
                    var sto = Ext.getStore('tempDatas');
                    var dd = Ext.decode(getdataserver);
                    sto.loadRawData(dd, true);

                    var v = Ext.create('login.view.userinfovew',{});
                    v.show();
                    this.getView().destroy();
                }
            }
        };

        httpc.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
        httpc.send("username="+username+"&password="+password);
    },

    onSignUp: function(button, e, eOpts) {
        console.log('I am work');
        var vv = Ext.create('login.view.pageSignup');
        vv.show();
        this.getView().destroy();
    },

    onLoginWinClose: function(panel, eOpts) {
        var v = Ext.create('login.view.MyViewport',{});
        v.show();
    }

});
