/*
 * File: app/view/Logwin.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('login.view.Logwin', {
    extend: 'Ext.window.Window',
    alias: 'widget.logwin',

    requires: [
        'login.view.LogwinViewModel',
        'login.view.LogwinViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.form.Label'
    ],

    controller: 'logwin',
    viewModel: {
        type: 'logwin'
    },
    height: 419,
    resizable: false,
    width: 396,
    layout: 'fit',
    title: 'Login',

    items: [
        {
            xtype: 'form',
            height: 314,
            width: 470,
            layout: 'absolute',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    x: 10,
                    y: 180,
                    id: 'i_userid',
                    width: 336,
                    fieldLabel: 'UserID'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    x: 10,
                    y: 230,
                    id: 'i_pass',
                    width: 347,
                    fieldLabel: 'Password',
                    inputType: 'password'
                },
                {
                    xtype: 'button',
                    x: 270,
                    y: 340,
                    height: 30,
                    width: 100,
                    text: 'Sign In',
                    listeners: {
                        click: 'onSignIn'
                    }
                },
                {
                    xtype: 'button',
                    x: 40,
                    y: 340,
                    height: 30,
                    width: 100,
                    text: 'Sign Up',
                    listeners: {
                        click: 'onSignUp'
                    }
                },
                {
                    xtype: 'image',
                    x: 120,
                    y: -3,
                    height: 140,
                    width: 140,
                    alt: 'ridoykj',
                    src: 'ico/lock.png'
                },
                {
                    xtype: 'label',
                    x: 120,
                    y: 270,
                    id: 'l_status',
                    text: 'Status: '
                }
            ]
        }
    ],
    listeners: {
        close: 'onLoginWinClose'
    }

});