/*
 * File: app/view/pageSignup.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('login.view.pageSignup', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.pagesignup',

    requires: [
        'login.view.pageSignupViewModel',
        'login.view.pageSignupViewController',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.button.Button',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Text',
        'Ext.form.Label'
    ],

    controller: 'pagesignup',
    viewModel: {
        type: 'pagesignup'
    },
    height: 250,
    width: 400,
    layout: 'center',

    items: [
        {
            xtype: 'form',
            height: 491,
            id: 'signUpPage',
            width: 466,
            layout: 'absolute',
            bodyPadding: 10,
            closable: true,
            title: 'Registration From',
            items: [
                {
                    xtype: 'image',
                    x: 180,
                    y: 10,
                    height: 101,
                    width: 106,
                    alt: 'ridoykj',
                    src: 'ico/profile.png'
                },
                {
                    xtype: 'button',
                    x: 189,
                    y: 329,
                    disabled: true,
                    height: 35,
                    id: 'is_submit',
                    width: 94,
                    text: 'Submit',
                    listeners: {
                        click: 'onSubmit'
                    }
                },
                {
                    xtype: 'checkboxfield',
                    x: 130,
                    y: 296,
                    disabled: true,
                    id: 'is_ck',
                    boxLabel: ' I am read all terms and conditions'
                },
                {
                    xtype: 'textfield',
                    x: 53,
                    y: 183,
                    id: 'is_userid',
                    fieldLabel: 'UserID'
                },
                {
                    xtype: 'textfield',
                    x: 54,
                    y: 254,
                    disabled: true,
                    id: 'is_repass',
                    fieldLabel: 'Retype Password',
                    inputType: 'password'
                },
                {
                    xtype: 'textfield',
                    x: 53,
                    y: 218,
                    disabled: true,
                    id: 'is_pass',
                    fieldLabel: 'Password',
                    inputType: 'password'
                },
                {
                    xtype: 'label',
                    x: 60,
                    y: 140,
                    height: 42,
                    id: 'is_status',
                    width: 329,
                    text: 'Status:'
                },
                {
                    xtype: 'button',
                    x: 340,
                    y: 180,
                    height: 30,
                    width: 80,
                    text: 'Check',
                    listeners: {
                        click: 'onUseridCheck'
                    }
                }
            ],
            listeners: {
                close: 'onSignUpPageClose'
            }
        }
    ]

});