/*
 * File: app/view/pageSignupViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('login.view.pageSignupViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pagesignup',

    onSubmit: function(button, e, eOpts) {
        var username = Ext.getCmp('is_userid').value;
        var password = Ext.getCmp('is_pass').value;
        var repassword = Ext.getCmp('is_repass').value;
        if(username === '' && password === '')
        {
            Ext.getCmp('is_status').setText('Status: Please Fill userid and password');
        }
        else if(password != repassword)
        {
            Ext.getCmp('is_status').setText('Status: Please retype same Password');
        }
        else if(!Ext.getCmp('is_ck').getValue())
        {
            Ext.getCmp('is_status').setText('Status: Please Read our trams and condtion');
        }
        else{

            Ext.Ajax.request({
                url: 'php/signup.php',
                method: 'POST',
                params: {'userid': username, 'password': password },
                headers:
                {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },

                success: function(response, opts) {
                    var d = response.responseText;
                    console.log(d);
                    Ext.getCmp('is_status').setText('Status: Profile successfully created');
                },

                failure: function(response, opts) {
                    console.log('server-side failure with status code ' + response.status);
                }
            });

        }
    },

    onSignUpPageClose: function(panel, eOpts) {
        var show = Ext.widget('logwin');
        show.show();
    },

    onUseridCheck: function(button, e, eOpts) {
        var username = Ext.getCmp('is_userid').value;

        Ext.Ajax.request({
            url: 'php/query.php',
            method: 'POST',
            params: {'userid': username},
            headers:
            {
                'Content-Type': 'application/x-www-form-urlencoded'
            },

            success: function(response, opts) {
                var d = response.responseText;
                console.log(d);
                if(username === '')
                {
                    Ext.getCmp('is_status').setText('Status: Please Enter User id');
                }
                else if(d != 'true')
                {
                    Ext.getCmp('is_status').setText('Status: Found New User id');
                    Ext.getCmp('is_submit').setDisabled(false);
                    Ext.getCmp('is_pass').setDisabled(false);
                    Ext.getCmp('is_repass').setDisabled(false);
                    Ext.getCmp('is_ck').setDisabled(false);
                }else
                {
                    Ext.getCmp('is_status').setText('Status: The UserID already exists');
                }
            },

            failure: function(response, opts) {
                console.log('server-side failure with status code ' + response.status);
            }
        });
    }

});
