/*
 * File: app/view/userinfovew.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('login.view.userinfovew', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.userinfovew',

    requires: [
        'login.view.userinfovewViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'userinfovew'
    },
    height: 250,
    width: 400,
    layout: 'fit',

    items: [
        {
            xtype: 'gridpanel',
            height: 250,
            width: 400,
            title: 'User Information',
            store: 'tempDatas',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userid',
                    text: 'Userid'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'pass',
                    text: 'Pass'
                }
            ]
        }
    ]

});